development:
  adapter: mysql2
  database: fakturan_dev
  encoding: utf8
  host: 127.0.0.1
  username: root
  password:

test:
  adapter: mysql2
  database: fakturan_test
  encoding: utf8
  host: 127.0.0.1
  username: root
  password:

# Never enter login info here, set it on the server
production:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: gitit_production
  username: gitit
  password: <%= ENV['GITIT_DATABASE_PASSWORD'] %>
  socket: /var/run/mysqld/mysqld.sock
